name: First Workflow

on: workflow_dispatch

jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World"
      - name: Print Goodbye
        run: echo "Done Bye!!!"
      - name: Multiline text
        run: |
          echo "First output"
          echo "Second output"
